version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "swift"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.9"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "php"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/KOSASIH/AgriPro"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["AgriPro"]

[[analyzers]]
name = "ansible"

[[transformers]]
name = "swift-format"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "ktlint"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "standardrb"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "black"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"

[[transformers]]
name = "isort"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "gofumpt"

[[transformers]]
name = "gofmt"